### ISSUE TITLE
Dili niya madetect akong mask

### ISSUE THREAD

**Issue by HamzaSultansarip** [miaabbygaleflores/FMTD-DSP-Project#7]
![418a3dd666f36fc88447994c4b68552c](https://user-images.githubusercontent.com/95402234/149352360-40dad559-c165-4652-a414-acb81ff385fc.jpg)

**Comment by HamzaSultansarip** [comment]
HAHAHAHAHAHAHAHA

**Comment by miaabbygaleflores** [comment]
dami time mangbash ah HAHAHAHAAHAHAHA

**Comment by miaabbygaleflores** [comment]
> HAHAHAHAHAHAHAHA

dami time mangbash ah HAHAHAHAAHAHAHA

**Comment by miaabbygaleflores** [comment]
> HAHAHAHAHAHAHAHA

daming time mangbash ah HAHAHAHAAHAHAHA
